
INSERT INTO USER_DETAILS(USER_ID, FIRST_NAME, LAST_NAME, SEX, AGE, ADDRESS, EXISTING_DISEASES) VALUES (1, 'CHANDRA','BK','MALE',21,'KCC','NA');

INSERT INTO ROLE_DETAILS(email, password, role, user_id) VALUES('chandra@gmail.com', 'test123', 'ADMIN', 1);

