DROP TABLE IF EXISTS USER_DETAILS;

DROP TABLE IF EXISTS ROLE_DETAILS;

DROP TABLE IF EXISTS BOOKING_DETAILS;

DROP TABLE IF EXISTS CONTACT_DETAILS;

CREATE TABLE USER_DETAILS(USER_ID INT PRIMARY KEY AUTO_INCREMENT, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), SEX VARCHAR(255), AGE INT, ADDRESS VARCHAR(255), EXISTING_DISEASES VARCHAR(255), QUALIFICATION VARCHAR(255), SPECIALIZATION VARCHAR(255), YEAR_OF_EXP VARCHAR(255)); 

CREATE TABLE ROLE_DETAILS(role_id INT PRIMARY KEY AUTO_INCREMENT, email VARCHAR(255), password VARCHAR(255), role VARCHAR(100), USER_ID INT);

CREATE TABLE BOOKING_DETAILS(BOOKING_ID INT PRIMARY KEY AUTO_INCREMENT, BOOKED_DATE VARCHAR(255), BOOKED_TIME VARCHAR(255), 
DOCTOR_ID INT, TREATMENT_TYPE VARCHAR(255), PURPOSE VARCHAR(255), 
PATIENT_ID INT, IS_TREATMENT_COMPLETED VARCHAR(255), PRESCRIPTION VARCHAR(255));

CREATE TABLE CONTACT_DETAILS (CONTACT_ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), COUNTRY_CODE NUMBER(2), PHONE_NUMBER NUMBER(12), EMAIL VARCHAR(50), ADDRESS VARCHAR(255), BRANCH CHAR, SUB_BRANCH CHAR, HEAD_OFFICE CHAR);
