DROP TABLE IF EXISTS USER_DETAILS;

DROP TABLE IF EXISTS ROLE_DETAILS;

DROP TABLE IF EXISTS BOOKING_DETAILS;

CREATE TABLE USER_DETAILS(USER_ID INT PRIMARY KEY AUTO_INCREMENT, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), SEX VARCHAR(255), AGE INT, ADDRESS VARCHAR(255), EXISTING_DISEASES VARCHAR(255)); 
CREATE TABLE ROLE_DETAILS(role_id INT PRIMARY KEY AUTO_INCREMENT, email VARCHAR(255), password VARCHAR(255), role VARCHAR(100), USER_ID INT);
CREATE TABLE BOOKING_DETAILS(BOOKING_ID INT PRIMARY KEY AUTO_INCREMENT, BOOKED_DATE VARCHAR(255), BOOKED_TIME VARCHAR(255), 
DOCTOR_NAME VARCHAR(255), TREATMENT_TYPE VARCHAR(255), PURPOSE VARCHAR(255), PROFILE_ID INT, 
PATIENT_NAME VARCHAR(255), IS_TREATMENT_COMPLETED VARCHAR(255), PRESCRIPTION VARCHAR(255), USER_ID INT);


--INSERT INTO USER_DETAILS(USER_ID, FIRST_NAME, LAST_NAME, SEX, AGE, ADDRESS, EXISTING_DISEASES) VALUES (1, 'CHANDRA','BK','MALE',21,'KCC','NA');
--INSERT INTO ROLE_DETAILS(email, password, role, user_id) VALUES('email', 'test123', 'ADMIN', 1);

